version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "kind/dependency"
      - "area/ci"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/editors/vscode"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:45"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "kind/dependency"
      - "area/tooling"
    commit-message:
      prefix: "tooling"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:50"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "kind/dependency"
      - "area/docs"
    commit-message:
      prefix: "site"
      include: "scope"
