#!/usr/bin/env python3
"""Seed wall-clock harness for packaged check/fmt/help.

This is a local timing seed, not a headline performance claim. Numeric
thresholds are recorded only after two local runs; this suite does not
enforce them. Exit 1 only when a non-skipped command fails (unexpected
return code). Missing ``sh`` writes a SKIP report and exits 0.
"""
from __future__ import annotations

import argparse
import os
import platform
import shlex
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Sequence

from repo_support import bind_relative_path, write_json_atomic

ROOT = Path(__file__).resolve().parents[1]
rel = bind_relative_path(ROOT, resolve=True)
REPORT_KIND = "ouro.bench-suite.v1"
# Thresholds only after two local runs.
THRESHOLD_POLICY = (
    "Numeric wall-clock thresholds are not enforced yet; this seed records "
    "host timings only until two local runs exist."
)


@dataclass(frozen=True)
class Case:
    name: str
    argv: tuple[str, ...]
    expected_returncode: int


CASES: tuple[Case, ...] = (
    Case("check-io", ("scripts/ouro1.sh", "check", "std/io.ouro"), 0),
    Case("fmt-check-io", ("scripts/ouro1.sh", "fmt", "--check", "std/io.ouro"), 0),
    # ouro1 help prints usage and exits 2; that is the success path.
    Case("help", ("scripts/ouro1.sh", "help"), 2),
)


def resolve_sh() -> str | None:
    found = shutil.which("sh")
    if found:
        return found
    roots = [os.environ.get("ProgramFiles", r"C:\Program Files")]
    pf86 = os.environ.get("ProgramFiles(x86)")
    if pf86:
        roots.append(pf86)
    for root in roots:
        for rel_sh in (Path("Git") / "bin" / "sh.exe", Path("Git") / "usr" / "bin" / "sh.exe"):
            candidate = Path(root) / rel_sh
            if candidate.is_file():
                return str(candidate)
    return None


def host_meta() -> dict[str, str]:
    return {
        "system": platform.system(),
        "machine": platform.machine(),
        "python_version": platform.python_version(),
    }


def write_markdown(path: Path, report: dict[str, Any]) -> None:
    lines = [
        "# Ouro bench suite",
        "",
        f"Status: `{report['status']}`",
        (
            "Host: `{system}` `{machine}` Python `{python_version}`".format(
                **report["host"]
            )
        ),
        "",
        "| Name | Elapsed ms | Return | Skipped | Command |",
        "| --- | ---: | ---: | --- | --- |",
    ]
    for row in report["commands"]:
        rc = row["returncode"]
        rc_text = "" if rc is None else str(rc)
        skipped = "yes" if row["skipped"] else "no"
        lines.append(
            "| {name} | {elapsed} | {rc} | {skipped} | `{cmd}` |".format(
                name=row["name"],
                elapsed=row["elapsed_ms"],
                rc=rc_text,
                skipped=skipped,
                cmd=shlex.join(row["argv"]),
            )
        )
    lines.extend(
        [
            "",
            THRESHOLD_POLICY,
            "",
            "Generated by `python3 scripts/bench_suite.py`.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def skipped_row(case: Case) -> dict[str, Any]:
    return {
        "name": case.name,
        "argv": ["sh", *case.argv],
        "elapsed_ms": 0,
        "returncode": None,
        "skipped": True,
    }


def run_case(case: Case, env: dict[str, str], sh: str) -> dict[str, Any]:
    argv = [sh, *case.argv]
    print(f"BENCH_START {case.name} cmd={shlex.join(argv)}")
    started = time.perf_counter()
    proc = subprocess.run(
        argv,
        cwd=ROOT,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    elapsed_ms = round((time.perf_counter() - started) * 1000.0, 3)
    ok = proc.returncode == case.expected_returncode
    print(
        f"BENCH_DONE {case.name} rc={proc.returncode} expected={case.expected_returncode} "
        f"elapsed_ms={elapsed_ms} ok={int(ok)}"
    )
    if not ok and proc.stdout:
        tail = proc.stdout.splitlines()[-40:]
        for line in tail:
            print(line)
    return {
        "name": case.name,
        "argv": argv,
        "elapsed_ms": elapsed_ms,
        "returncode": proc.returncode,
        "skipped": False,
        "expected_returncode": case.expected_returncode,
        "ok": ok,
    }


def write_report(out: Path, *, status: str, commands: list[dict[str, Any]], skip_reason: str | None, started: float) -> Path:
    report = {
        "kind": REPORT_KIND,
        "status": status,
        "pass": status != "FAIL",
        "out": rel(out),
        "host": host_meta(),
        "policy": {"thresholds": THRESHOLD_POLICY},
        "skip_reason": skip_reason,
        "commands": commands,
        "elapsed_ms": round((time.perf_counter() - started) * 1000.0, 3),
    }
    json_path = out / "report.json"
    md_path = out / "report.md"
    write_json_atomic(json_path, report)
    write_markdown(md_path, report)
    print(f"BENCH_SUITE: {status} report={rel(json_path)}")
    return json_path


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="_build/bench", help="report directory (default: _build/bench)")
    args = ap.parse_args(argv)

    out = Path(args.out)
    if not out.is_absolute():
        out = ROOT / out
    out.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()

    sh = resolve_sh()
    if sh is None:
        commands = [skipped_row(case) for case in CASES]
        write_report(out, status="SKIP", commands=commands, skip_reason="sh not found", started=started)
        return 0

    env = os.environ.copy()
    env.setdefault("OURO_ROOT", str(ROOT))
    env.setdefault("PYTHON", sys.executable)
    sh_dir = str(Path(sh).resolve().parent)
    env["PATH"] = sh_dir + os.pathsep + env.get("PATH", "")

    commands = [run_case(case, env, sh) for case in CASES]
    failed = [row for row in commands if not row.get("skipped") and not row.get("ok")]
    status = "FAIL" if failed else "PASS"
    write_report(out, status=status, commands=commands, skip_reason=None, started=started)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
