#!/usr/bin/env python3
"""Run Ouro's fail-closed memory budget corpus."""
from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional, Sequence

from ourosmith.host import BUILD_MEMORY_MB
from ourosmith.limits import run_limited
from repo_support import bind_relative_path, read_json_value, write_json_atomic

ROOT = Path(__file__).resolve().parents[1]
rel = bind_relative_path(ROOT, resolve=True)
REPORT_KIND = "ouro.memory-budget-suite-report.v1"
# Synthetic source above scripts/analyze_bounded.py MAX_DRIVE_FILE_BYTES; written
# under _build so the guard does not depend on any production file's size.
OVERSIZED_STRUCTURED_FIXTURE = Path("_build/memory/fixtures/oversized_structured.ouro")
OVERSIZED_STRUCTURED_BYTES = 40960 + 4096


def write_oversized_structured_fixture() -> None:
    target = ROOT / OVERSIZED_STRUCTURED_FIXTURE
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = ["-- generated by scripts/memory_budget_suite.py; must exceed the drive limit", ""]
    index = 0
    size = sum(len(line) + 1 for line in lines)
    while size <= OVERSIZED_STRUCTURED_BYTES:
        line = f"def oversized_{index} (n : Nat) : Nat := n;"
        lines.append(line)
        size += len(line) + 1
        index += 1
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


@dataclass(frozen=True)
class Case:
    label: str
    budget_id: str
    cmd: list[str]
    description: str
    blocking: bool = True
    env: dict[str, str] = field(default_factory=dict)
    # One accepted exit code, or several when the verdict is not the point.
    expected_returncode: int | tuple[int, ...] = 0
    required_output: str | None = None

    def accepts_returncode(self, returncode: object) -> bool:
        if isinstance(self.expected_returncode, tuple):
            return returncode in self.expected_returncode
        return returncode == self.expected_returncode


# Per-file families of ouro-analyze-drive, as scripts/analyze_bounded.py
# accepts them; the unions (--enable-all/--enable-heavy) are global flags.
DRIVE_FAMILIES = (
    "effects",
    "capability",
    "extract",
    "match",
    "cfg",
    "dataflow",
    "semantic",
    "property",
    "absint",
    "symexec",
    "taint",
    "contracts",
    "metrics",
    "duplication",
    "simplify",
    "perf",
    "naming",
    "errors",
)



def largest_production_source() -> str:
    """Keep the budget on the largest input after refactors, not an old filename."""
    candidates = (path for scope in ("std", "compiler", "tools/analyze", "tools")
                  for path in (ROOT / scope).rglob("*.ouro"))
    largest = max(candidates, key=lambda path: (path.stat().st_size, path.as_posix()))
    return largest.relative_to(ROOT).as_posix()


CASES: tuple[Case, ...] = (
    Case(
        "tool-emission-collect",
        "tool-emission-collect",
        ["sh", "scripts/build_tool.sh", "tools/collect.ouro", "_build/memory/bin/ouro-collect"],
        "collect install path must not enter the old multi-GiB selfhost emitter",
    ),
    Case(
        "tool-emission-fmt",
        "tool-emission-fmt",
        ["sh", "scripts/build_tool.sh", "tools/fmt.ouro", "_build/memory/bin/ouro-fmt"],
        "formatter install path must remain bounded",
    ),
    Case(
        "tool-emission-analyze",
        "tool-emission-analyze",
        ["sh", "scripts/build_tool.sh", "tools/analyze/main.ouro", "_build/memory/bin/ouro-analyze"],
        "analyzer install path must remain bounded",
    ),

    Case(
        "native-check-fmt",
        "native-check-fmt",
        ["sh", "scripts/ouro1.sh", "check", "tools/fmt.ouro", "60000"],
        "native multi-unit compiler check path for tools/fmt; exercises frontend phase lifetime, not wrapper-only install",
        env={"OURO_MEM_TRACE": "1"},
    ),
    Case(
        "native-check-analyze",
        "native-check-analyze",
        ["sh", "scripts/ouro1.sh", "check", "tools/analyze/main.ouro", "60000"],
        "native multi-unit compiler check path for tools/analyze; catches large analyzer closure RSS regressions",
        env={"OURO_MEM_TRACE": "1"},
    ),
    Case(
        "native-check-analyze-drive",
        "native-check-analyze",
        ["sh", "scripts/ouro1.sh", "check", "tools/analyze/drive_main.ouro", "60000"],
        "wide structured analyzer cone must release per-expression lowering temporaries",
        env={"OURO_MEM_TRACE": "1"},
        required_output="CHECK_OK",
    ),
    Case(
        "native-c-build-jobs2",
        "native-c-build-jobs2",
        [sys.executable, "scripts/ouro_build.py", "build", "--jobs", "2"],
        "native C bootstrap build with the configured incremental object path",
    ),
    Case(
        "import-heavy-batch",
        "import-heavy-batch",
        ["sh", "scripts/ouro1.sh", "collect", "quality/fixtures/memory/import_heavy/root.ouro"],
        "synthetic import fan-in closure collection",
    ),
    Case(
        "formatter-suite",
        "formatter-suite",
        ["sh", "scripts/fmt_suite.sh"],
        "formatter goldens, idempotence, write mode, and tree drift",
        env={"FMT_SUITE_OUT": "_build/memory/fmt_suite"},
    ),
    Case(
        "analyzer-batch",
        "analyzer-batch",
        [
            "sh",
            "scripts/ouro1.sh",
            "analyze",
            "--strict",
            "--include-fixtures",
            "--scope",
            "tests/analyze/architecture_good",
            "--scope",
            "tests/analyze/deadcode_good",
        ],
        "strict analyzer over representative good fixture batches",
    ),
    Case(
        "analyzer-std-api-hash",
        "analyzer-std-api-hash",
        ["sh", "scripts/ouro1.sh", "analyze", "--strict", "--scope", "std/args.ouro"],
        "strict std API hashing must stay bounded for a small public module",
    ),
    Case(
        "analyzer-bounded-tree",
        "analyzer-bounded-tree",
        ["sh", "scripts/ouro1.sh", "analyze", "--strict", "--scope", "tools/analyze"],
        "strict analyzer over a production tree must use file-local process isolation",
    ),
    Case(
        "analyzer-structured-large-guard",
        "analyzer-structured-large-guard",
        [
            "sh",
            "scripts/ouro1.sh",
            "analyze",
            "--strict",
            "--enable-effects",
            "--scope",
            OVERSIZED_STRUCTURED_FIXTURE.as_posix(),
        ],
        "oversized structured inputs must fail before the native drive starts",
        expected_returncode=1,
        required_output="ANALYZE_FAIL: structured analyzer file exceeds the local safety limit",
    ),
    Case(
        "analyzer-drive-largest-file",
        "analyzer-drive-largest-file",
        [
            "sh",
            "scripts/ouro1.sh",
            "analyze",
            "--strict",
            *(f"--enable-{family}" for family in DRIVE_FAMILIES),
            "--scope",
            largest_production_source(),
        ],
        "every structured family over the largest production source in one native drive process",
        # Opt-in families report on production code until the triage pass;
        # the budget measures the process, not the verdict.
        expected_returncode=(0, 1),
        required_output="ANALYZE_DRIVE ",
    ),
    Case(
        "analyzer-enable-all",
        "analyzer-enable-all",
        ["sh", "scripts/ouro1.sh", "analyze", "--strict", "--enable-all", "--scope", "tools/analyze"],
        "large global analyzer families must fail closed before native analyzers start",
        expected_returncode=1,
        required_output="ANALYZE_FAIL: global analyzer flags require a bounded scope",
    ),
    Case(
        "small-source",
        "small-source",
        ["sh", "scripts/ouro1.sh", "check", "quality/fixtures/memory/tiny.ouro", "5000"],
        "tiny source check",
    ),
    Case(
        "medium-selfhost-module",
        "medium-selfhost-module",
        ["sh", "scripts/ouro1.sh", "check", "quality/fixtures/memory/medium.ouro", "14000"],
        "medium representative source check",
    ),
    Case(
        "strict-quality-gate",
        "strict-quality-gate",
        [
            sys.executable,
            "scripts/strict_quality_firewall.py",
            "--profile",
            "release",
            "--report",
            "_build/memory/strict-quality-firewall.json",
            "--sarif",
            "_build/memory/strict-quality-firewall.sarif",
            "--migration-report",
            "_build/memory/strict-quality-migration.md",
        ],
        "release strict-quality firewall under a budget",
    ),
    Case(
        "docs-examples-gate",
        "docs-examples-gate",
        [sys.executable, "scripts/docs_examples_gate.py", "--work", "_build/memory/docs_examples", "--report", "_build/memory/docs_examples.json"],
        "docs/examples drift gate under a budget",
    ),
    Case(
        "stage-loop-smoke",
        "stage-loop-smoke",
        [sys.executable, "scripts/ouro_build.py", "build", "--jobs", "1"],
        "representative C bootstrap build smoke instead of full stage-loop",
    ),
)


def prepare_tools(cases: Sequence[Case], out: Path) -> list[dict[str, Any]]:
    """Keep native compilation outside the existing execution RSS budgets.

    The measured install cases still run unchanged. Preparation checks full
    source receipts, so an old binary or unrelated cache hit cannot stand in
    for the selected tool. Build failures are blocking and recorded separately.
    """
    labels = {case.label for case in cases}
    tools: list[tuple[str, str]] = []
    if labels & {"native-check-fmt", "native-check-analyze", "native-check-analyze-drive",
                 "import-heavy-batch", "small-source", "medium-selfhost-module"}:
        tools.append(("tools/collect.ouro", "ouro-collect"))
    if "formatter-suite" in labels:
        tools.append(("tools/fmt.ouro", "ouro-fmt"))
    if any(label.startswith("analyzer-") for label in labels):
        tools.append(("tools/analyze/main.ouro", "ouro-analyze"))
    if "analyzer-drive-largest-file" in labels:
        tools.append(("tools/analyze/drive_main.ouro", "ouro-analyze-drive"))
    if "docs-examples-gate" in labels:
        tools.append(("tools/repo_gate/main.ouro", "ouro-repo-gate"))
    directory = Path(os.environ.get("OURO_C_BUILD_DIR", str(ROOT / "_build/c")))
    if not directory.is_absolute():
        directory = ROOT / directory
    compiler = Path(os.environ.get("OURO1_COMPILER", str(directory / "ouro1")))
    reports: list[dict[str, Any]] = []
    for entry, name in tools:
        command = [sys.executable, "scripts/native_tool_build.py", entry,
                   str(directory / name), "--compiler", str(compiler)]
        print(f"MEMORY_PREPARE_START {name}", flush=True)
        result = run_limited(command, cwd=ROOT, env=os.environ,
                             timeout_s=900, memory_mb=BUILD_MEMORY_MB)
        log = out / f"prepare-{name}.log"
        log.write_text(result.stdout + result.stderr, encoding="utf-8")
        reports.append({"tool": name, "command": command, "status": result.classify(),
                        "returncode": result.returncode, "elapsed_s": result.elapsed_s,
                        "memory_mb": BUILD_MEMORY_MB, "log": rel(log)})
        write_json_atomic(out / "preparation.json", {"pass": result.ok, "tools": reports})
        print(f"MEMORY_PREPARE_DONE {name} status={result.classify()} log={rel(log)}", flush=True)
        if not result.ok:
            raise SystemExit(f"memory budget: native tool preparation failed: {name}; see {rel(log)}")
    return reports


def load_json_object(path: Path, *, what: str) -> dict[str, Any]:
    data, error = read_json_value(path)
    if error is not None:
        raise SystemExit(f"memory budget: cannot read {what} {path}: {error}")
    if not isinstance(data, dict):
        raise SystemExit(f"memory budget: {what} {path} is not a JSON object")
    return data


def load_budgets(path: Path) -> dict[str, Any]:
    data = load_json_object(path, what="budget file")
    budgets = data.get("budgets")
    if not isinstance(budgets, dict):
        raise SystemExit(f"memory budget file missing budgets object: {path}")
    return data


def budget_kb(budgets: dict[str, Any], budget_id: str) -> int:
    entry = budgets["budgets"].get(budget_id)
    if not isinstance(entry, dict) or "peak_rss_kb" not in entry:
        raise SystemExit(f"missing memory budget: {budget_id}")
    return int(entry["peak_rss_kb"])


def case_log_name(label: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in label)


def run_case(case: Case, *, out: Path, budgets: dict[str, Any], sample_interval: float) -> dict[str, Any]:
    budget = budget_kb(budgets, case.budget_id)
    stem = case_log_name(case.label)
    json_path = out / f"{stem}.json"
    md_path = out / f"{stem}.md"
    log_path = out / f"{stem}.log"
    env = os.environ.copy()
    env.setdefault("OURO_ROOT", str(ROOT))
    env.setdefault("PYTHON", sys.executable)
    env.setdefault("OURO_BUILD_TOOL_MODE", "auto")
    env.setdefault("OURO_C_BUILD_DIR", str(ROOT / "_build" / "c"))
    env.setdefault("OURO_CI", "1")
    for key, value in case.env.items():
        env[key] = str(ROOT / value) if value.startswith("_build/") else value
    watch_cmd = [
        sys.executable,
        "scripts/memory_watch.py",
        "--label",
        case.label,
        "--budget-kb",
        str(budget),
        "--cwd",
        str(ROOT),
        "--json",
        str(json_path),
        "--markdown",
        str(md_path),
        "--sample-interval",
        str(sample_interval),
        "--",
        *case.cmd,
    ]
    print(f"MEMORY_CASE_START {case.label} budget_kb={budget} cmd={shlex.join(case.cmd)}")
    started = time.perf_counter()
    with log_path.open("w", encoding="utf-8") as log:
        proc = subprocess.run(watch_cmd, cwd=ROOT, env=env, text=True, stdout=log, stderr=subprocess.STDOUT)
    elapsed = round(time.perf_counter() - started, 6)
    report: dict[str, Any] | None = None
    if json_path.exists():
        try:
            loaded = json.loads(json_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError):
            loaded = None
        if isinstance(loaded, dict):
            report = loaded
    report_available = report is not None
    if report is None:
        report = {
            "kind": "ouro.memory-watch-report.v1",
            "label": case.label,
            "command": case.cmd,
            "returncode": proc.returncode,
            "elapsed_s": elapsed,
            "peak_rss_kb": 0,
            "budget_kb": budget,
            "budget_status": "fail",
            "measurement": {"note": "memory_watch did not produce JSON"},
        }
    try:
        log_text = log_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        log_text = ""
    output_ok = case.required_output is None or case.required_output in log_text
    measurement = report.get("measurement")
    terminated_for_budget = (
        bool(measurement.get("terminated_for_budget"))
        if isinstance(measurement, dict)
        else False
    )
    memory_budget_met = (
        report_available
        and int(report.get("peak_rss_kb", budget + 1)) <= budget
        and not terminated_for_budget
    )
    status = (
        "pass"
        if case.accepts_returncode(report.get("returncode"))
        and memory_budget_met
        and output_ok
        else "fail"
    )
    result = {
        **report,
        "suite_status": status,
        "blocking": case.blocking,
        "description": case.description,
        "expected_returncode": case.expected_returncode,
        "required_output": case.required_output,
        "required_output_found": output_ok,
        "memory_budget_met": memory_budget_met,
        "budget_id": case.budget_id,
        "log": rel(log_path),
        "json": rel(json_path),
        "markdown": rel(md_path),
    }
    print(
        f"MEMORY_CASE_DONE {case.label} status={status} rc={report.get('returncode')} "
        f"peak_rss_kb={report.get('peak_rss_kb')} budget_kb={budget} elapsed_s={report.get('elapsed_s')} log={rel(log_path)}"
    )
    if status == "fail":
        try:
            tail = log_path.read_text(encoding="utf-8", errors="replace").splitlines()[-60:]
        except OSError:
            tail = []
        for line in tail:
            print(line)
    return result


def write_summary(out: Path, report: dict[str, Any]) -> None:
    lines = [
        "# Ouro memory budget summary",
        "",
        f"Pass: `{'yes' if report['pass'] else 'no'}`",
        f"Elapsed: `{report['elapsed_s']}s`",
        "",
        "| Case | Status | Peak RSS | Budget | Baseline delta | Command |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    for case in report["cases"]:
        delta = case.get("baseline_delta_kb")
        delta_text = "n/a" if delta is None else f"{delta:+d} KiB"
        lines.append(
            "| {label} | {status} | {peak} KiB | {budget} KiB | {delta} | `{cmd}` |".format(
                label=case["label"],
                status=case["suite_status"],
                peak=case.get("peak_rss_kb", 0),
                budget=case.get("budget_kb", 0),
                delta=delta_text,
                cmd=shlex.join(case.get("command", [])),
            )
        )
    lines.extend([
        "",
        "Generated by `python3 scripts/memory_budget_suite.py`.",
        "",
    ])
    (out / "memory-summary.md").write_text("\n".join(lines), encoding="utf-8")


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--budgets", default="quality/memory_budgets.json")
    ap.add_argument("--baseline", default="quality/memory_baseline.json")
    ap.add_argument("--out", default="_build/memory")
    ap.add_argument("--case", action="append", default=[])
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--sample-interval", type=float, default=0.05)
    args = ap.parse_args(argv)

    selected = list(CASES)
    if args.case:
        wanted = set(args.case)
        selected = [case for case in selected if case.label in wanted or case.budget_id in wanted]
        missing = wanted - {case.label for case in selected} - {case.budget_id for case in selected}
        if missing:
            raise SystemExit("unknown memory case(s): " + ", ".join(sorted(missing)))
    if args.list:
        for case in selected:
            print(f"{case.label}\t{case.budget_id}\t{shlex.join(case.cmd)}")
        return 0

    budget_path = Path(args.budgets)
    if not budget_path.is_absolute():
        budget_path = ROOT / budget_path
    budgets = load_budgets(budget_path)
    baseline_path = Path(args.baseline)
    if not baseline_path.is_absolute():
        baseline_path = ROOT / baseline_path
    baseline: dict[str, Any] = {}
    if baseline_path.exists():
        baseline = load_json_object(baseline_path, what="baseline")
    out = Path(args.out)
    if not out.is_absolute():
        out = ROOT / out
    out.mkdir(parents=True, exist_ok=True)

    started = time.perf_counter()
    preparation = prepare_tools(selected, out)
    if any(case.label == "analyzer-structured-large-guard" for case in selected):
        write_oversized_structured_fixture()
    results = [run_case(case, out=out, budgets=budgets, sample_interval=max(0.01, args.sample_interval)) for case in selected]
    baseline_cases = baseline.get("cases", {}) if isinstance(baseline, dict) else {}
    for result in results:
        entry = baseline_cases.get(result.get("label")) if isinstance(baseline_cases, dict) else None
        if isinstance(entry, dict) and "peak_rss_kb" in entry:
            base_peak = int(entry["peak_rss_kb"])
            peak = int(result.get("peak_rss_kb", 0))
            result["baseline_peak_rss_kb"] = base_peak
            result["baseline_delta_kb"] = peak - base_peak
            result["baseline_delta_pct"] = None if base_peak == 0 else round(((peak - base_peak) * 100.0) / base_peak, 3)
    failed = [case for case in results if case.get("blocking") and case.get("suite_status") != "pass"]
    report = {
        "kind": REPORT_KIND,
        "pass": not failed,
        "budget_file": rel(budget_path),
        "baseline_file": rel(baseline_path) if baseline_path.exists() else None,
        "out": rel(out),
        "cases": results,
        "preparation": preparation,
        "blocking_failures": failed,
        "elapsed_s": round(time.perf_counter() - started, 6),
        "policy": {
            "peak_rss": "budgeted compiler behavior; blocking cases fail closed on rc != 0 or peak > budget",
            "native_tool_emission": "native multi-unit check paths are budgeted as first-class cases; host wrappers remain bounded install UX fallbacks and are reported separately",
            "reports": "per-case JSON/markdown/log plus aggregate memory-report.json and memory-summary.md",
        },
        "budgets": budgets,
        "baseline": baseline,
    }
    write_json_atomic(out / "memory-report.json", report)
    write_summary(out, report)
    print(f"MEMORY_BUDGET_SUMMARY pass={int(not failed)} cases={len(results)} report={rel(out / 'memory-report.json')}")
    return 0 if not failed else 1


if __name__ == "__main__":
    raise SystemExit(main())
